# Generated by Django 5.2.1 on 2025-06-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urfe', '0002_zettel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_materials',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='urfe.material'),
        ),
    ]
