# Generated by Django 5.2.2 on 2025-06-05 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urfe', '0003_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_materials',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Напишіть кілька слів про себе (до 20 слів).', max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='Опис не може перевищувати 20 слів (100 символів).')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Користувач'), ('moderator', 'Модератор'), ('admin', 'Адміністратор')], default='user', max_length=20),
        ),
    ]
