# Generated by Django 5.2.2 on 2025-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urfe', '0004_remove_userprofile_favorite_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_materials',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='urfe.material'),
        ),
    ]
